### PR TITLE
fix: retry queries on each node

### LINKED ISSUE #15: Use Improved UI-kit for RPC (dapp-inter-jumper)
We need to update rpc connection logic for dapp-inter-jumper to improve UX

## Description of the Design

Use improved UI-kit for RPC for dapp-inter-jumper to improve RPC node experience -> https://github.com/Agoric/ui-kit/issues/56

### PR DESCRIPTION
**Pull request by samsiegart**
fixes https://github.com/Agoric/dapp-inter-jumper/issues/15

Contrary to the issue description, this dapp doesn't use ui-kit in order to keep the bundle size small, as it's just a redirect page. Instead, this implements the retry logic described in https://github.com/Agoric/ui-kit/issues/56

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export const timeoutDurationMS = 5_000;
```
Comment (turadg) [inline src/constants.ts:5]: Consider documenting here that this timeout is for each attempt, how many attempts there will be, and what feedback the user gets

File: src/vstorage-query.ts [hunk 2]
```diff
@@ -1,7 +1,67 @@
-import { abciQuery } from './abci-query';
+import { timeoutDurationMS } from './constants';
 
-export const vstorageQuery = async (
-  node: string,
-  path: string,
-  blockHeight?: number
-) => abciQuery(node, `/custom/vstorage/data/${path}`, blockHeight);
+const getNodeIterator = (nodes: string[]) => {
```
Comment (turadg) [inline src/vstorage-query.ts]: this reads like it's an Iterator but it's just different enough to be confusing. Please return an actual [JS Iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)

```js
interface IteratorReturnResult<TReturn> {
    done: true;
    value: TReturn;
}
interface Iterator<T, TReturn = any, TNext = undefined> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return?(value?: TReturn): IteratorResult<T, TReturn>;
    throw?(e?: any): IteratorResult<T, TReturn>;
}
```

```suggestion
const getNodeIterator = (nodes: string[]): Iterator<string> => {
```

File: src/vstorage-query.ts [hunk 3]
```diff
@@ -1,7 +1,67 @@
...
+
+  const requestPromises = [];
+  const resolvers: [(value: unknown) => void, (reason?: any) => void][] = [];
+  for (let i = 0; i < nodes.length; i++) {
+    requestPromises.push(
+      new Promise((resolve, reject) => {
+        resolvers.push([resolve, reject]);
+      })
+    );
+  }
```
Comment (turadg) [inline src/vstorage-query.ts]: @endo/promise-kit was made for this scenario, but I get this app should be light.

Please simplify though. When reading the mutation looks like it might change.

```suggestion
  const requestPromises = nodes.map(() => 
      new Promise((resolve, reject) => {
        resolvers.push([resolve, reject]);
    );
  );
```

File: src/main.ts [hunk 4]
```diff
@@ -104,18 +108,30 @@ const tryRedirect = async () => {
...
-  const rpc = networkConfig.rpc;
-  const banner = networkConfig.banner;
-  const timeoutDurationMS = 10_000;
+  const { apiAddrs, banner } = networkConfig;
   let redirectUrl: URL | undefined = undefined;
+  let didFail = false;
+
+  setTimeout(() => {
+    if (!didFail && !redirectUrl) {
+      showError('Connection is taking longer than expected. Please wait.');
```
Comment (turadg) [inline src/main.ts:117]: nice touch

File: src/main.ts [hunk 5]
```diff
@@ -104,18 +108,30 @@ const tryRedirect = async () => {
...
 
   try {
-    redirectUrl = await (Promise.race([
-      getRedirectUrl(rpc),
-      new Promise((_, rej) => setTimeout(rej, timeoutDurationMS)),
-    ]) as Promise<URL>);
+    redirectUrl = await getRedirectUrl(apiAddrs);
   } catch {
-    showError('No endorsed UI found.');
+    // Retry once as specified in https://github.com/Agoric/ui-kit/issues/56
```
Comment (turadg) [inline src/main.ts]:
```suggestion
    // Retry all nodes once more as specified in https://github.com/Agoric/ui-kit/issues/56
```

File: src/vstorage-query.ts [hunk 6]
```diff
@@ -1,7 +1,67 @@
...
+ * Queries a vstorage path from a random node from `nodes`. Every
+ * `timeoutDurationMS`, it will queue up another request to a new node until
+ * all nodes are exhausted, returning the first result it gets.
+ *
+ * @param nodes The API nodes to request vstorage data from
+ * @param path The vstorage path
+ * @returns The vstorage query result
+ */
+export const vstorageQuery = async (nodes: string[], path: string) => {
+  const nodeIterator = getNodeIterator(nodes);
```
Comment (turadg) [inline src/vstorage-query.ts]: Consider moving "twice through" logic here.
```suggestion
  const nodesRepeatedOnce = [...nodes, ...nodes];
  const nodeIterator = getNodeIterator(nodesRepeatedOnce);
```

File: src/vstorage-query.ts [hunk 7]
```diff
@@ -1,7 +1,67 @@
...
+  for (let i = 0; i < nodes.length; i++) {
+    requestPromises.push(
+      new Promise((resolve, reject) => {
+        resolvers.push([resolve, reject]);
+      })
+    );
+  }
+
+  let queueFetchInterval: number | undefined = undefined;
+  let currentNodeIndex = 0;
```
Comment (turadg) [inline src/vstorage-query.ts]: IIUC,
```suggestion
  let nextNodeIndex = 0;
```

File: src/vstorage-query.ts [hunk 8]
```diff
@@ -1,7 +1,67 @@
...
+    }
+  };
+
+  queueFetch(nodeIterator.next());
+  queueFetchInterval = setInterval(() => {
+    queueFetch(nodeIterator.next());
+  }, timeoutDurationMS);
+
+  try {
+    // @ts-expect-error if .json() doesn't exist, fetch error is implied and handled in main.ts.
```
Comment (turadg) [inline src/vstorage-query.ts]: This suppresses the whole line, not just the .json. Consider breaking it up

File: src/vstorage-query.ts [hunk 9]
```diff
@@ -1,7 +1,67 @@
...
+    return (await Promise.any(requestPromises)).json();
```
Comment (turadg) [inline src/vstorage-query.ts]: This function could be sync by returning this promise.
```suggestion
    const response = Promise.any(requestPromises);
    return response.then(r => r.json());
```
After writing that, I'm neutral on it

File: src/vstorage-query.ts (hunk 2 above)
Comment (gibson042) [reply src/vstorage-query.ts]: FWIW, there's also a convention in SwingSet (albeit a weak one) to prefix the name of such functions with "enumerate". And in this case also I think "node" is misleading because there are both RPC nodes and storage nodes(neither of which are relevant to the implementation), and more substantially that there might be benefit in mixing up the order in each block of the nodes. Suggestion:
```typescript
/**
 * Enumerates an infinite sequence composed of elements from
 * successive Fisher-Yates shuffles of an array.
 *
 * @param elements
 * @returns An iterator
 */
const enumerateShuffles = <T,>(elements: T[]): Iterator<T> => {
  const indices = elements.map((_element, i) => i);
  // https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm
  const shuffleIndices = () => {
    for (let i = indices.length - 1; i >= 1; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = indices[j];
      indices[j] = indices[i];
      indices[i] = tmp;
    }
  };

  let i = elements.length;
  const next: () => IteratorResult<T> = () => {
    i += 1;
    if (i >= elements.length) {
      shuffleIndices();
      i = 0;
    }
    return { done: false, value: elements[indices[i]] };
  };
  return { next };
};
```

File: src/constants.ts (hunk 1 above)
Comment (samsiegart) [reply src/constants.ts:5]: Done

File: src/vstorage-query.ts (hunk 2 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Incorporated @gibson042's suggestion

File: src/vstorage-query.ts (hunk 3 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Done

File: src/main.ts (hunk 5 above)
Comment (samsiegart) [reply src/main.ts]: Moved the retry inside vstorage-query.ts where it's more self-explanatory

File: src/vstorage-query.ts (hunk 6 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Did something different here, but similar effect

File: src/vstorage-query.ts (hunk 7 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Changed this to actually be the current index starting at -1 when there's no fetch happening yet

File: src/vstorage-query.ts (hunk 8 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Done

File: src/vstorage-query.ts (hunk 9 above)
Comment (samsiegart) [reply src/vstorage-query.ts]: Just split the await into a different line, more clear for the ts-ignore

**Review by turadg — APPROVED** [review]
