### PR TITLE
fix: hack to enable smallcaps

### LINKED ISSUE #6: open-coded vstorage client doesn't support smallcaps
https://github.com/Agoric/dapp-inter-jumper/blob/a5f08f4608ced13d5963fdb5eb2e4ccdc9adeca3/src/main.ts#L44-L49

### PR DESCRIPTION
**Pull request by FUDCo**
Closes #6

### CODE REVIEW

**Review by samsiegart — APPROVED** [review]
LGTM!

File: src/main.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ const tryRedirect = async () => {
     const { values } = JSON.parse(data.value);
     const latestValue = values[values.length - 1];
     const value = JSON.parse(latestValue);
-    const body = JSON.parse(value.body);
+    const body = JSON.parse(value.body.substring(1));
```
Comment (dckc) [inline src/main.ts:48]: Did we consider back compatibility using `.replace(/^#/, '')`?

Comment (turadg) [reply src/main.ts:48]: +1 to forward/backward compatibility. dunno if it's reason to push again but it's a good practice
